# Custom command-not-found handler with insults

command_not_found_handler () {
    local INSULTS=(
        "Boooo !"
        "Don't you know anything ?"
        "I will leave you a minute to let you think about what you just did"
        "RTFM !"
        "Hahaha, n00b !"
        "Wow! That was impressively wrong !"
        "What are you doing ??"
        "Pathetic"
        "The worst one today !"
        "n00b alert !"
        "lol"
        "You failed me 💔"
        ":("
        "I hope no one is seeing this..."
        "It is so embarrassing"
        "Wow, you suck !"
        "lol... plz"
        "plz uninstall"
        "And the Darwin Award goes to.... ${USER} !"
        "ERROR_INCOMPETENT_USER"
        "Incompetence is also competence"
        "Bad."
        "Fake it till you make it!"
        "What is this ? Amateur hour !?"
        "Come on! You can do it !"
        "Nice try."
        "What if... you type an actual command the next time !"
        "What if I told you... it is possible to type valid commands."
        "Y u no speak computer ???"
        "This is not Windows"
        "Perhaps you should leave the command line alone..."
        "Please step away from the keyboard !"
        "error code: 1D10T"
        "Pro tip: type a valid command !"
        "Go outside."
        "Go sit by a lake"
        "Wait... What ?"
        "At least you tried"
        "Why me ? 😢"
        "🤔"
        "U tried 😕"
        "Dude, WTF ?"
        "Are you sure you are qualified to use computers ?"
        "Take a deep breath and try again"
        "Maybe you should lie down for a few minutes"
        "You should press the buttons in the correct order"
        "This is not a search engine."
        "So, I'm just going to go ahead and run rm -rf / for you."
        "Why are you so stupid?!"
        "Perhaps computers are not for you..."
        "Why are you doing this to me ?!"
        "Don't you have anything better to do ?!"
        "I am _seriously_ considering 'rm -rf /'-ing myself..."
        "This is why nobody likes you."
        "Are you even trying ?!"
    )

    /usr/lib/command-not-found --no-failure-msg -- ${1+"$1"}
    printf "$(tput bold)$(tput setaf 1)$(shuf -n 1 -e "${INSULTS[@]}")$(tput sgr0)"
    echo ""

    # Return the exit code normally returned on invalid command
    return 127
}
